stages:
  - test
  - deploy
  - docker

include:
  - file: /Auto/npm.yml
    project: jitesoft/gitlab-ci-lib

docker-deploy:
  stage: docker
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  tags:
    - protected
    - buildx
  script:
    - MAJOR=$(echo $CI_COMMIT_TAG | cut -f1 -d'.')
    - MINOR=$(echo $CI_COMMIT_TAG | cut -f2 -d'.')
    - PATCH=$(echo $CI_COMMIT_TAG | cut -f3 -d'.')
    - docker buildx build --platform linux/amd64,linux/arm64 --push -t ${CI_REGISTRY_IMAGE}:${MAJOR} -t ${CI_REGISTRY_IMAGE}:${MAJOR}${MINOR} -t ${CI_REGISTRY_IMAGE}:${MAJOR}${MINOR}${PATCH} -t ${CI_REGISTRY_IMAGE}:latest .
  rules:
    - if: '$CI_COMMIT_TAG'
      when: delayed
      start_in: '5 minutes'
    - when: never
